name: Check and Lint

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  workflow_run:
    workflows:
      - Auto Format
    types:
      - completed

permissions:
  contents: read

jobs:
  check:
    if: github.event_name != 'workflow_run' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_repository.full_name == github.repository)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: github.event_name != 'workflow_run'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Checkout formatted branch
        if: github.event_name == 'workflow_run'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Oxlint
        id: lint
        run: pnpm lint
        continue-on-error: true

      - name: Format Check
        id: format
        run: pnpm fmt:check
        continue-on-error: true

      - name: Type Check
        id: typecheck
        run: pnpm typecheck
        continue-on-error: true

      - name: React Router Build
        id: build
        run: pnpm run build
        continue-on-error: true

      - name: Fail if any checks failed
        if: |
          always() &&
          (
            steps.lint.outcome == 'failure' ||
            steps.format.outcome == 'failure' ||
            steps.typecheck.outcome == 'failure' ||
            steps.build.outcome == 'failure'
          )
        run: |
          echo "One or more checks failed."
          exit 1
