name: Check Lint Format

on:
  pull_request:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26.3.0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Oxlint
        run: pnpm exec oxlint .

      - name: Oxfmt Check
        run: pnpm exec oxc_format --check .

      - name: Type Check
        run: pnpm run typecheck

      - name: React Router Build
        run: pnpm run build
